### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Yummot** [Yummot/dpusys_hw#2]
Here is the roadmap for the HW part of our project.

- [x] Automation: Add a Makefile or build scripts if possible.
  - [x] Figure out how to automatically build a Vivado project.
- [x] Evaluate and build more configurations for the Xilinx DPU. This is to create a different Vivado project with different DPU configuration for our project evaluation. Some possible configurations may be:
  - [x] B4096, 1 core.
  - B4096, 3 cores. (No feasible for implementation in ZCU102, closed).
  - [x] B1152, 2 cores.
  - [x] B1152, 1 core.
  - etc.
- [x] Improve the design performance.
  - [x] The video pipeline Subsystem.
  - [x] The DPU subsystem.
- [x] Improve the project TCL scripts if possible.

**Comment by Yummot** [comment]
Add hw projects:
- 1core, B1152 00ab217c95b59e9f417e98025183a53aa86f1346
- 2core, B1152 439098c19668b23882d835efa02ce29970a2c0df
- 1core, B4096 8e33d7e1d016750734967dac060642396fd60383

**Comment by Yummot** [comment]
Add experimental Makefile and build related TCL scripts. 8e33d7e1d016750734967dac060642396fd60383
Pass build tests.

**Comment by Yummot** [comment]
B4096, 3core HW project will run out of DSP units of ZCU102. Thus, no B4096, 3core project will be added.

**Comment by Yummot** [comment]
More conf projects are added:
- 2core B2304 project f34c19639973a6a20361cc3287b3b645e39ef49d
- 2core B1024 project cbbfbd61506b27d95986d425a2a92ca90f616b1c
- 1core B2304 project af6c9c69116a825f59e38d2f469e1767afd81135
- 1core B1024 project af6c9c69116a825f59e38d2f469e1767afd81135

**Comment by Yummot** [comment]
Add prebuilt folder which contains prebuilt HSI. b7c842fb6df20e23ea113cee308d9ebd4010437d
